scp method5_upgrade_fix_run_as_sys.sql bbam-pfopl01:/home/oracle 
scp method5_upgrade_fix_run_as_sys.sql csco-orapl01:/home/oracle 
scp method5_upgrade_fix_run_as_sys.sql csco-orapl03:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql davldb0149:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql g02orapl01:/home/oracle
scp method5_upgrade_fix_run_as_sys.sql gef-hyopl01:/home/oracle 
scp method5_upgrade_fix_run_as_sys.sql ibm-orapl01:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql iex-orapl01:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql iex-orapl02:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql iex-orapl03:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql ing-hyopl01:/home/oracle 
scp method5_upgrade_fix_run_as_sys.sql jaf-orapl11:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql lear-phopl01:/home/oracle 
scp method5_upgrade_fix_run_as_sys.sql mga-hyopl01:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql mycc-hyopl01:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql npos-orapl01:/home/oracle 
scp method5_upgrade_fix_run_as_sys.sql pilorapl01:/home/oracle
scp method5_upgrade_fix_run_as_sys.sql thcorapl01:/home/oracle  
scp method5_upgrade_fix_run_as_sys.sql wcm-orapl11:/home/oracle 
scp method5_upgrade_fix_run_as_sys.sql xpvldb0011:/home/oracle
scp method5_upgrade_fix_run_as_sys.sql emb-hyopl01:/home/oracle
scp method5_upgrade_fix_run_as_sys.sql emb-ofnpl01:/home/oracle
scp method5_upgrade_fix_run_as_sys.sql emb-ohcpl01:/home/oracle
scp method5_upgrade_fix_run_as_sys.sql emb-orapl01:/home/oracle
scp method5_upgrade_fix_run_as_sys.sql emb-ovcpl01:/home/oracle
