scp m5_run_shell_script.sql bbam-pfopl01:/home/oracle 
scp m5_run_shell_script.sql csco-orapl01:/home/oracle 
scp m5_run_shell_script.sql csco-orapl03:/home/oracle  
scp m5_run_shell_script.sql davldb0149:/home/oracle  
scp m5_run_shell_script.sql g02orapl01:/home/oracle
scp m5_run_shell_script.sql gef-hyopl01:/home/oracle 
scp m5_run_shell_script.sql ibm-orapl01:/home/oracle  
scp m5_run_shell_script.sql iex-orapl01:/home/oracle  
scp m5_run_shell_script.sql iex-orapl02:/home/oracle  
scp m5_run_shell_script.sql iex-orapl03:/home/oracle  
scp m5_run_shell_script.sql ing-hyopl01:/home/oracle 
scp m5_run_shell_script.sql jaf-orapl11:/home/oracle  
scp m5_run_shell_script.sql lear-phopl01:/home/oracle 
scp m5_run_shell_script.sql mga-hyopl01:/home/oracle  
scp m5_run_shell_script.sql mycc-hyopl01:/home/oracle  
scp m5_run_shell_script.sql npos-orapl01:/home/oracle 
scp m5_run_shell_script.sql pilorapl01:/home/oracle
scp m5_run_shell_script.sql thcorapl01:/home/oracle  
scp m5_run_shell_script.sql wcm-orapl11:/home/oracle 
scp m5_run_shell_script.sql xpvldb0011:/home/oracle
scp m5_run_shell_script.sql emb-hyopl01:/home/oracle
scp m5_run_shell_script.sql emb-ofnpl01:/home/oracle
scp m5_run_shell_script.sql emb-ohcpl01:/home/oracle
scp m5_run_shell_script.sql emb-orapl01:/home/oracle
scp m5_run_shell_script.sql emb-ovcpl01:/home/oracle
