scp method5_install_v5.sql bbam-pfopl01:/home/oracle 
scp method5_install_v5.sql csco-orapl01:/home/oracle 
scp method5_install_v5.sql csco-orapl03:/home/oracle  
scp method5_install_v5.sql davldb0149:/home/oracle  
scp method5_install_v5.sql g02orapl01:/home/oracle
scp method5_install_v5.sql gef-hyopl01:/home/oracle 
scp method5_install_v5.sql ibm-orapl01:/home/oracle  
scp method5_install_v5.sql iex-orapl01:/home/oracle  
scp method5_install_v5.sql iex-orapl02:/home/oracle  
scp method5_install_v5.sql iex-orapl03:/home/oracle  
scp method5_install_v5.sql ing-hyopl01:/home/oracle 
scp method5_install_v5.sql jaf-orapl11:/home/oracle  
scp method5_install_v5.sql lear-phopl01:/home/oracle 
scp method5_install_v5.sql mga-hyopl01:/home/oracle  
scp method5_install_v5.sql mycc-hyopl01:/home/oracle  
scp method5_install_v5.sql npos-orapl01:/home/oracle 
scp method5_install_v5.sql pilorapl01:/home/oracle
scp method5_install_v5.sql thcorapl01:/home/oracle  
scp method5_install_v5.sql wcm-orapl11:/home/oracle 
scp method5_install_v5.sql xpvldb0011:/home/oracle
scp method5_install_v5.sql emb-hyopl01:/home/oracle
scp method5_install_v5.sql emb-ofnpl01:/home/oracle
scp method5_install_v5.sql emb-ohcpl01:/home/oracle
scp method5_install_v5.sql emb-orapl01:/home/oracle
scp method5_install_v5.sql emb-ovcpl01:/home/oracle
