S24DBA@OEM12DG1 > /
scp method5_install_v5.sql agii-oracl02:/home/oracle                                
scp method5_install_v5.sql agii-oradl01:/home/oracle                                
scp method5_install_v5.sql agii-oradl01:/home/oracle                                
scp method5_install_v5.sql agii-oradl02:/home/oracle                                
scp method5_install_v5.sql agii-oraeml01:/home/oracle                               
scp method5_install_v5.sql agii-oraeml03:/home/oracle                               
scp method5_install_v5.sql agii-orafinl01:/home/oracle                              
scp method5_install_v5.sql agii-orafinl02:/home/oracle                              
scp method5_install_v5.sql agii-oraprfl01:/home/oracle                              
scp method5_install_v5.sql agii-oraprtl01:/home/oracle                              
scp method5_install_v5.sql agii-oraql01:/home/oracle                                
scp method5_install_v5.sql agii-oraql01:/home/oracle                                
scp method5_install_v5.sql agii-oraql01:/home/oracle                                
scp method5_install_v5.sql agii-oraql01:/home/oracle                                
scp method5_install_v5.sql agii-oraql02:/home/oracle                                
scp method5_install_v5.sql agii-oraql03:/home/oracle                                
scp method5_install_v5.sql agii-oraql03:/home/oracle                                
scp method5_install_v5.sql agii-oraql04:/home/oracle                                
scp method5_install_v5.sql agii-orasl01:/home/oracle                                
scp method5_install_v5.sql agii-oratrnl01:/home/oracle                              
scp method5_install_v5.sql agii-oratrnl02:/home/oracle                              
scp method5_install_v5.sql agii-oraul01:/home/oracle                                
scp method5_install_v5.sql agii-oraul02:/home/oracle                                
scp method5_install_v5.sql agii-oraul02:/home/oracle                                
scp method5_install_v5.sql agii-oraul02:/home/oracle                                
scp method5_install_v5.sql agii-oraul03:/home/oracle                                
scp method5_install_v5.sql agii-oraul03:/home/oracle                                
scp method5_install_v5.sql agii-oraul03:/home/oracle                                
scp method5_install_v5.sql asf-oradl01:/home/oracle                                 
scp method5_install_v5.sql euhplmtest01:/home/oracle                                
scp method5_install_v5.sql gef-hyodl01:/home/oracle                                 
scp method5_install_v5.sql gef-hyoql01:/home/oracle                                 
scp method5_install_v5.sql ibm-oradl01:/home/oracle                                 
scp method5_install_v5.sql ibm-oraql01:/home/oracle                                 
scp method5_install_v5.sql iex-oradl01:/home/oracle                                 
scp method5_install_v5.sql iex-oradl02:/home/oracle                                 
scp method5_install_v5.sql iex-oradl03:/home/oracle                                 
scp method5_install_v5.sql ing_hyodl01:/home/oracle                                 
scp method5_install_v5.sql ing_hyoql01:/home/oracle                                 
scp method5_install_v5.sql mga-hyoql02:/home/oracle                                 
scp method5_install_v5.sql mil-oradw01:/home/oracle                                 
scp method5_install_v5.sql mil-oraqw02:/home/oracle                                 
scp method5_install_v5.sql mycc-hyoql01:/home/oracle                                
scp method5_install_v5.sql tab-oradl01:/home/oracle                                 
scp method5_install_v5.sql ticf-oradl02:/home/oracle                                
scp method5_install_v5.sql ticf-oradl03:/home/oracle                                
scp method5_install_v5.sql ushplmdev01:/home/oracle                                 
scp method5_install_v5.sql ushplmtraning01:/home/oracle                             

S24DBA@OEM12DG1 > spool off/
