SQL> select method5.method5_admin.generate_link_test_script(
  2      p_link_name =>     'M5_EBTPROD.PRD.MSP.ORACLE.DB',
  3      p_database_name => 'EBTPROD.PRD.MSP.ORACLE.DB',
  4      p_host_name =>     'agii-orap105',
  5      p_port_number =>   '1528')
  6  from dual;

METHOD5.METHOD5_ADMIN.GENERATE_LINK_TEST_SCRIPT(P_LINK_NAME=>'M5_EBTPROD.PRD.MSP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
--------------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
----------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
--#1: Test a Method5 database link.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
--                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

SQL> spool off;
